packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@effect/vitest": "4.0.0-rc.112"
  effect: "4.0.0-rc.112"
  viem: "2.56.0"
  vitest: "4.1.11"

allowBuilds:
  esbuild: true
  lefthook: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - viem@2.56.0
