import type { DefaultTheme } from "vitepress";

const slug = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const title = (value: string) => {
  const moduleName = value.split("/").at(-1) ?? value;
  return moduleName
    .split("-")
    .map(
      (part) =>
        ({
          dns: "DNS",
          dnssec: "DNSSEC",
          ens: "ENS",
          erc: "ERC",
          eth: "ETH",
          hca: "HCA",
          l2: "L2",
          v1: "V1",
          v2: "V2",
        })[part] ?? part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join(" ");
};

const apiGroup = (
  base: string,
  text: string,
  names: ReadonlyArray<string>,
): DefaultTheme.SidebarItem => ({
  collapsed: true,
  items: names.map((name) => ({ link: `${base}/${slug(name)}`, text: name })),
  text,
});

const contractGroup = (text: string, modules: ReadonlyArray<string>): DefaultTheme.SidebarItem => ({
  collapsed: true,
  items: modules.map((module) => ({ link: `/contracts/api/${module}`, text: title(module) })),
  text,
});

const actionGroups = {
  batch: [
    "estimateCalls",
    "executeWritePlan",
    "getCallsStatus",
    "getWalletCapabilities",
    "prepareCalls",
    "readBatch",
    "readBatchSettled",
    "resumeCalls",
    "sendCalls",
    "simulateCalls",
  ],
  capabilities: [
    "getNameCapabilities",
    "getOperatorApproval",
    "getRecordPermissions",
    "getRegistryCapabilities",
    "getRegistryRoles",
    "getRequiredAuthorization",
    "getResolverCapabilities",
    "getResolverDelegateApproval",
    "getResolverRoles",
    "getTokenApproval",
    "getWrapperPermissions",
    "getWriteTarget",
    "hasRegistryRoles",
    "hasResolverRoles",
  ],
  dns: [
    "claimDnsName",
    "getDnsClaimStatus",
    "getDnsImportPlan",
    "getDnsRecord",
    "getDnsRecords",
    "getZoneHash",
    "hasDnsRecords",
    "importDnsName",
    "setDnsRecords",
    "setZoneHash",
  ],
  events: ["getEnsEvents", "getNameHistory", "watchEnsEvents"],
  migration: [
    "approveMigration",
    "getMigrationEligibility",
    "getMigrationPlan",
    "getMigrationStatus",
    "getMigrationTarget",
    "migrateName",
    "migrateNames",
  ],
  name: [
    "getCanonicalResource",
    "getExpiry",
    "getManager",
    "getNameState",
    "getNameStatus",
    "getOwner",
    "getProtocol",
    "getRegistrant",
    "getRegistry",
    "getTokenId",
    "isAvailable",
    "isMigrated",
    "isRenewable",
    "isReserved",
    "isWrapped",
  ],
  ownership: [
    "getTtl",
    "reclaimName",
    "setManager",
    "setTtl",
    "transferName",
    "transferRegistrant",
  ],
  permissions: [
    "approveName",
    "clearNameApproval",
    "grantRegistryRoles",
    "grantResolverRoles",
    "grantResolverRootRoles",
    "revokeRegistryRoles",
    "revokeResolverRoles",
    "revokeResolverRootRoles",
    "setOperatorApproval",
    "setRecordPermissions",
    "setResolverDelegateApproval",
  ],
  records: [
    "clearAvatar",
    "clearRecords",
    "getAbi",
    "getAddress",
    "getAddresses",
    "getAvatar",
    "getContentHash",
    "getData",
    "getInterface",
    "getName",
    "getPubkey",
    "getRecords",
    "getText",
    "getTexts",
    "setAbi",
    "setAddress",
    "setAddresses",
    "setAlias",
    "setAvatar",
    "setContentHash",
    "setData",
    "setInterface",
    "setName",
    "setPubkey",
    "setRecords",
    "setText",
    "setTexts",
  ],
  registration: [
    "approvePaymentToken",
    "approveRenewalPayment",
    "commitName",
    "completeRegistration",
    "getCommitmentStatus",
    "getRegistrationParameters",
    "getRegistrationPlan",
    "getRegistrationPrice",
    "getRenewalPrice",
    "isPaymentTokenSupported",
    "makeRegistrationCommitment",
    "registerName",
    "registerNames",
    "renewName",
    "renewNames",
  ],
  resolution: [
    "createResolver",
    "getAlias",
    "getOrCreateResolver",
    "getResolver",
    "getResolverVersion",
    "predictResolverAddress",
    "resolve",
    "resolveBatch",
    "resolveWithResolver",
    "setResolver",
    "setResolverAndRecords",
    "upgradeResolver",
  ],
  reverse: [
    "clearPrimaryName",
    "getPrimaryName",
    "setContractPrimaryName",
    "setPrimaryName",
    "setPrimaryNameForAddress",
  ],
  subnames: [
    "createSubname",
    "deleteSubname",
    "setSubnameExpiry",
    "setSubnameManager",
    "setSubnameRecord",
    "setSubnameResolver",
    "transferSubname",
  ],
  wrapping: [
    "extendSubnameExpiry",
    "getFuses",
    "getWrapperExpiry",
    "setChildFuses",
    "setFuses",
    "unwrapName",
    "wrapName",
  ],
} as const;
const hookGroups = {
  context: ["useEnsforge", "useEnsforgeRegistry"],
  cache: ["useInvalidate"],
  batch: [
    "useReadBatch",
    "useReadBatchSettled",
    "useEstimateCalls",
    "useEstimateCallsSuspense",
    "useCallsStatus",
    "useCallsStatusSuspense",
    "useWalletCapabilities",
    "useWalletCapabilitiesSuspense",
    "usePrepareCalls",
    "usePrepareCallsSuspense",
    "useSimulateCalls",
    "useSimulateCallsSuspense",
    "useExecuteWritePlan",
    "useResumeCalls",
    "useSendCalls",
  ],
  capabilities: [
    "useNameCapabilities",
    "useNameCapabilitiesSuspense",
    "useOperatorApproval",
    "useOperatorApprovalSuspense",
    "useRecordPermissions",
    "useRecordPermissionsSuspense",
    "useRegistryCapabilities",
    "useRegistryCapabilitiesSuspense",
    "useRegistryRoles",
    "useRegistryRolesSuspense",
    "useRequiredAuthorization",
    "useRequiredAuthorizationSuspense",
    "useResolverCapabilities",
    "useResolverCapabilitiesSuspense",
    "useResolverDelegateApproval",
    "useResolverDelegateApprovalSuspense",
    "useResolverRoles",
    "useResolverRolesSuspense",
    "useTokenApproval",
    "useTokenApprovalSuspense",
    "useWrapperPermissions",
    "useWrapperPermissionsSuspense",
    "useWriteTarget",
    "useWriteTargetSuspense",
    "useHasRegistryRoles",
    "useHasRegistryRolesSuspense",
    "useHasResolverRoles",
    "useHasResolverRolesSuspense",
  ],
  dns: [
    "useDnsClaimStatus",
    "useDnsClaimStatusSuspense",
    "useDnsImportPlan",
    "useDnsImportPlanSuspense",
    "useDnsRecord",
    "useDnsRecordSuspense",
    "useDnsRecords",
    "useDnsRecordsSuspense",
    "useZoneHash",
    "useZoneHashSuspense",
    "useHasDnsRecords",
    "useHasDnsRecordsSuspense",
    "useClaimDnsName",
    "useImportDnsName",
    "useSetDnsRecords",
    "useSetZoneHash",
  ],
  events: [
    "useEnsEvents",
    "useEnsEventsSuspense",
    "useNameHistory",
    "useNameHistorySuspense",
    "useWatchEnsEvents",
  ],
  migration: [
    "useMigrationEligibility",
    "useMigrationEligibilitySuspense",
    "useMigrationPlan",
    "useMigrationPlanSuspense",
    "useMigrationStatus",
    "useMigrationStatusSuspense",
    "useMigrationTarget",
    "useMigrationTargetSuspense",
    "useApproveMigration",
    "useMigrateName",
    "useMigrateNames",
  ],
  name: [
    "useCanonicalResource",
    "useCanonicalResourceSuspense",
    "useExpiry",
    "useExpirySuspense",
    "useManager",
    "useManagerSuspense",
    "useNameState",
    "useNameStateSuspense",
    "useNameStatus",
    "useNameStatusSuspense",
    "useOwner",
    "useOwnerSuspense",
    "useProtocol",
    "useProtocolSuspense",
    "useRegistrant",
    "useRegistrantSuspense",
    "useRegistry",
    "useRegistrySuspense",
    "useTokenId",
    "useTokenIdSuspense",
    "useIsAvailable",
    "useIsAvailableSuspense",
    "useIsMigrated",
    "useIsMigratedSuspense",
    "useIsRenewable",
    "useIsRenewableSuspense",
    "useIsReserved",
    "useIsReservedSuspense",
    "useIsWrapped",
    "useIsWrappedSuspense",
  ],
  ownership: [
    "useTtl",
    "useTtlSuspense",
    "useReclaimName",
    "useSetManager",
    "useSetTtl",
    "useTransferName",
    "useTransferRegistrant",
  ],
  permissions: [
    "useApproveName",
    "useClearNameApproval",
    "useGrantRegistryRoles",
    "useGrantResolverRoles",
    "useGrantResolverRootRoles",
    "useRevokeRegistryRoles",
    "useRevokeResolverRoles",
    "useRevokeResolverRootRoles",
    "useSetOperatorApproval",
    "useSetRecordPermissions",
    "useSetResolverDelegateApproval",
  ],
  records: [
    "useRecords",
    "useAbi",
    "useAbiSuspense",
    "useAddress",
    "useAddressSuspense",
    "useAddresses",
    "useAddressesSuspense",
    "useAvatar",
    "useAvatarSuspense",
    "useContentHash",
    "useContentHashSuspense",
    "useData",
    "useDataSuspense",
    "useInterface",
    "useInterfaceSuspense",
    "useNameRecord",
    "useNameRecordSuspense",
    "usePubkey",
    "usePubkeySuspense",
    "useText",
    "useTextSuspense",
    "useTexts",
    "useTextsSuspense",
    "useClearAvatar",
    "useClearRecords",
    "useSetAbi",
    "useSetAddress",
    "useSetAddresses",
    "useSetAlias",
    "useSetAvatar",
    "useSetContentHash",
    "useSetData",
    "useSetInterface",
    "useSetName",
    "useSetPubkey",
    "useSetRecords",
    "useSetText",
    "useSetTexts",
  ],
  registration: [
    "useCommitmentStatus",
    "useCommitmentStatusSuspense",
    "useRegistrationParameters",
    "useRegistrationParametersSuspense",
    "useRegistrationPlan",
    "useRegistrationPlanSuspense",
    "useRegistrationPrice",
    "useRegistrationPriceSuspense",
    "useRenewalPrice",
    "useRenewalPriceSuspense",
    "useIsPaymentTokenSupported",
    "useIsPaymentTokenSupportedSuspense",
    "useRegistrationCommitment",
    "useRegistrationCommitmentSuspense",
    "useApprovePaymentToken",
    "useApproveRenewalPayment",
    "useCommitName",
    "useCompleteRegistration",
    "useRegisterName",
    "useRegisterNames",
    "useRenewName",
    "useRenewNames",
  ],
  resolution: [
    "useAlias",
    "useAliasSuspense",
    "useResolver",
    "useResolverSuspense",
    "useResolverVersion",
    "useResolverVersionSuspense",
    "usePredictResolverAddress",
    "usePredictResolverAddressSuspense",
    "useResolve",
    "useResolveSuspense",
    "useResolveBatch",
    "useResolveBatchSuspense",
    "useResolveWithResolver",
    "useResolveWithResolverSuspense",
    "useCreateResolver",
    "useGetOrCreateResolver",
    "useSetResolver",
    "useSetResolverAndRecords",
    "useUpgradeResolver",
  ],
  reverse: [
    "usePrimaryName",
    "usePrimaryNameSuspense",
    "useClearPrimaryName",
    "useSetContractPrimaryName",
    "useSetPrimaryName",
    "useSetPrimaryNameForAddress",
  ],
  subnames: [
    "useCreateSubname",
    "useDeleteSubname",
    "useSetSubnameExpiry",
    "useSetSubnameManager",
    "useSetSubnameRecord",
    "useSetSubnameResolver",
    "useTransferSubname",
  ],
  wrapping: [
    "useFuses",
    "useFusesSuspense",
    "useWrapperExpiry",
    "useWrapperExpirySuspense",
    "useExtendSubnameExpiry",
    "useSetChildFuses",
    "useSetFuses",
    "useUnwrapName",
    "useWrapName",
  ],
} as const;
const contractGroups = {
  deployments: [
    "deployments/mainnet-v1",
    "deployments/sepolia-v1",
    "deployments/sepolia-v2",
    "deployments/types",
  ],
  shared: [
    "shared/erc1155",
    "shared/erc165",
    "shared/erc20",
    "shared/erc721",
    "shared/fragments/erc20",
    "shared/universal-resolver",
  ],
  resolverProfiles: [
    "shared/resolver-profiles/abi",
    "shared/resolver-profiles/addr",
    "shared/resolver-profiles/contenthash",
    "shared/resolver-profiles/data",
    "shared/resolver-profiles/dns-record",
    "shared/resolver-profiles/dns-zone",
    "shared/resolver-profiles/extended-resolver",
    "shared/resolver-profiles/interface",
    "shared/resolver-profiles/multicall",
    "shared/resolver-profiles/name",
    "shared/resolver-profiles/pubkey",
    "shared/resolver-profiles/text",
    "shared/resolver-profiles/versionable",
  ],
  v1Abis: [
    "v1/abis/base-registrar",
    "v1/abis/bulk-renewal",
    "v1/abis/default-reverse-registrar",
    "v1/abis/dns-registrar",
    "v1/abis/dnssec-oracle",
    "v1/abis/ens-registry",
    "v1/abis/eth-registrar-controller",
    "v1/abis/l2-reverse-registrar",
    "v1/abis/name-wrapper-upgrade",
    "v1/abis/name-wrapper",
    "v1/abis/offchain-dns-resolver",
    "v1/abis/price-oracle",
    "v1/abis/public-resolver",
    "v1/abis/reverse-registrar",
    "v1/abis/standalone-reverse-registrar",
    "v1/abis/universal-resolver",
    "v1/abis/wrapped-eth-registrar-controller",
  ],
  v1Fragments: [
    "v1/fragments/authorization",
    "v1/fragments/base-registrar",
    "v1/fragments/bulk-renewal",
    "v1/fragments/dns-registrar",
    "v1/fragments/ens-registry",
    "v1/fragments/eth-registrar-controller",
    "v1/fragments/expiry",
    "v1/fragments/name-wrapper",
    "v1/fragments/public-resolver",
    "v1/fragments/registration",
    "v1/fragments/resolution",
    "v1/fragments/reverse-registrar",
    "v1/fragments/universal-resolver",
  ],
  v1Constants: ["v1/constants/name-wrapper-fuses"],
  v2Abis: [
    "v2/abis/batch-registrar",
    "v2/abis/contract-namer",
    "v2/abis/default-reverse-registrar-adapter",
    "v2/abis/dns-v1-mirror-root-batch-registrar",
    "v2/abis/ens-v1-resolver",
    "v2/abis/ens-v2-resolver",
    "v2/abis/eth-registrar",
    "v2/abis/eth-registry",
    "v2/abis/eth-renewer-v1",
    "v2/abis/graveyard",
    "v2/abis/label-store",
    "v2/abis/locked-migration-controller",
    "v2/abis/managed-universal-resolver-proxy",
    "v2/abis/migration-helper",
    "v2/abis/permissioned-resolver",
    "v2/abis/public-resolver-set",
    "v2/abis/public-resolver",
    "v2/abis/registry-upgrade-set",
    "v2/abis/reverse-registrar-adapter",
    "v2/abis/root-registry",
    "v2/abis/standard-rent-price-oracle",
    "v2/abis/universal-resolver",
    "v2/abis/unlocked-migration-controller",
    "v2/abis/upgradable-universal-resolver-proxy",
    "v2/abis/user-registry",
    "v2/abis/verifiable-factory",
    "v2/abis/wrapper-registry",
  ],
  v2Fragments: [
    "v2/fragments/authorization",
    "v2/fragments/contract-namer",
    "v2/fragments/default-reverse-registrar-adapter",
    "v2/fragments/eth-registrar",
    "v2/fragments/eth-registry",
    "v2/fragments/eth-renewer-v1",
    "v2/fragments/expiry",
    "v2/fragments/migration-helper",
    "v2/fragments/permissioned-registry",
    "v2/fragments/permissioned-resolver",
    "v2/fragments/registration",
    "v2/fragments/renewal-batch",
    "v2/fragments/renewal",
    "v2/fragments/rent-price-oracle",
    "v2/fragments/resolution",
    "v2/fragments/standard-registry",
    "v2/fragments/tokenized-registry",
    "v2/fragments/universal-resolver",
    "v2/fragments/user-registry",
    "v2/fragments/verifiable-factory",
    "v2/fragments/wrapper-registry",
  ],
  v2Interfaces: [
    "v2/interfaces/address-set",
    "v2/interfaces/contract-name",
    "v2/interfaces/contract-namer",
    "v2/interfaces/default-reverse-registrar-adapter",
    "v2/interfaces/eac-grant-initializable",
    "v2/interfaces/enhanced-access-control",
    "v2/interfaces/erc1155-singleton",
    "v2/interfaces/eth-registrar",
    "v2/interfaces/eth-renewer",
    "v2/interfaces/l2-reverse-registrar",
    "v2/interfaces/label-store",
    "v2/interfaces/owned-registry",
    "v2/interfaces/permissioned-address-set",
    "v2/interfaces/permissioned-registry",
    "v2/interfaces/permissioned-resolver-initializable",
    "v2/interfaces/permissioned-resolver",
    "v2/interfaces/registry-events",
    "v2/interfaces/registry-uri-renderer",
    "v2/interfaces/registry",
    "v2/interfaces/rent-price-oracle-provider",
    "v2/interfaces/rent-price-oracle",
    "v2/interfaces/reverse-registrar-adapter",
    "v2/interfaces/standard-registry",
    "v2/interfaces/temporal-registry",
    "v2/interfaces/tokenized-registry",
    "v2/interfaces/universal-resolver",
    "v2/interfaces/universal-signature-validator",
    "v2/interfaces/wrapper-registry-initializable",
    "v2/interfaces/wrapper-registry",
  ],
  v2Constants: [
    "v2/constants/registry-interfaces",
    "v2/constants/registry-roles",
    "v2/constants/resolver-interfaces",
    "v2/constants/resolver-roles",
  ],
  experimentalHca: [
    "v2/experimental/hca/default-reverse-registrar-hca-adapter",
    "v2/experimental/hca/hca-authorizer",
    "v2/experimental/hca/hca-funding-session-validator",
    "v2/experimental/hca/hca-owner-and-session-validator",
    "v2/experimental/hca/hca-upgrade-gate",
    "v2/experimental/hca/standalone-hca-factory-interface",
    "v2/experimental/hca/standalone-hca-factory",
    "v2/experimental/hca/standalone-hca-owner-interface",
    "v2/experimental/hca/standalone-single-owner-hca",
    "v2/experimental/hca/trusted-hca-set",
  ],
} as const;

export const sidebar: DefaultTheme.Sidebar = {
  "/core/": [
    {
      items: [
        { link: "/core/why", text: "Why ensforge" },
        { link: "/core/installation", text: "Installation" },
        { link: "/core/getting-started", text: "Getting Started" },
        { link: "/core/effect", text: "Effect" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/core/guides/effect", text: "Effect" },
        { link: "/core/guides/error-handling", text: "Error Handling" },
        { link: "/core/guides/batching", text: "Batching" },
        { link: "/core/guides/protocol-routing", text: "Protocol Routing" },
        { link: "/core/guides/writes", text: "Writes" },
        { link: "/core/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    {
      items: [
        { link: "/core/api/create-config", text: "createConfig" },
        { link: "/core/api/create-wagmi-config", text: "createWagmiConfig" },
        { link: "/core/api/config", text: "Config" },
      ],
      text: "Configuration",
    },
    {
      items: [
        { link: "/core/api/actions", text: "Actions" },
        { link: "/core/api/schemas", text: "Schemas" },
        { link: "/core/api/errors", text: "Errors" },
        { link: "/core/api/write-plans", text: "Write Plans" },
      ],
      text: "API",
    },
    {
      collapsed: true,
      items: [
        { link: "/core/api/names", text: "Overview" },
        { link: "/core/api/names/normalize-name", text: "normalizeName" },
        { link: "/core/api/names/normalize-label", text: "normalizeLabel" },
        { link: "/core/api/names/analyze-name", text: "analyzeName" },
        { link: "/core/api/names/namehash", text: "namehash" },
        { link: "/core/api/names/labelhash", text: "labelhash" },
        { link: "/core/api/names/dns-encode-name", text: "dnsEncodeName" },
        { link: "/core/api/names/dns-decode-name", text: "dnsDecodeName" },
        { link: "/core/api/names/encode-address-record", text: "encodeAddressRecord" },
        { link: "/core/api/names/decode-address-record", text: "decodeAddressRecord" },
        { link: "/core/api/names/encode-content-hash", text: "encodeContentHash" },
        { link: "/core/api/names/decode-content-hash", text: "decodeContentHash" },
        { link: "/core/api/names/to-coin-type", text: "toCoinType" },
        { link: "/core/api/names/from-coin-type", text: "fromCoinType" },
      ],
      text: "Name Utilities",
    },
    apiGroup("/core/api/actions/batch", "Batch Actions", actionGroups.batch),
    apiGroup("/core/api/actions/capabilities", "Capabilities Actions", actionGroups.capabilities),
    apiGroup("/core/api/actions/dns", "Dns Actions", actionGroups.dns),
    apiGroup("/core/api/actions/events", "Events Actions", actionGroups.events),
    apiGroup("/core/api/actions/migration", "Migration Actions", actionGroups.migration),
    apiGroup("/core/api/actions/name", "Name Actions", actionGroups.name),
    apiGroup("/core/api/actions/ownership", "Ownership Actions", actionGroups.ownership),
    apiGroup("/core/api/actions/permissions", "Permissions Actions", actionGroups.permissions),
    apiGroup("/core/api/actions/records", "Records Actions", actionGroups.records),
    apiGroup("/core/api/actions/registration", "Registration Actions", actionGroups.registration),
    apiGroup("/core/api/actions/resolution", "Resolution Actions", actionGroups.resolution),
    apiGroup("/core/api/actions/reverse", "Reverse Actions", actionGroups.reverse),
    apiGroup("/core/api/actions/subnames", "Subnames Actions", actionGroups.subnames),
    apiGroup("/core/api/actions/wrapping", "Wrapping Actions", actionGroups.wrapping),
  ],
  "/sdk/": [
    {
      items: [
        { link: "/sdk/why", text: "Why ensforge" },
        { link: "/sdk/installation", text: "Installation" },
        { link: "/sdk/getting-started", text: "Getting Started" },
        { link: "/sdk/effect", text: "Effect" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/sdk/guides/grouped-actions", text: "Grouped Actions" },
        { link: "/sdk/guides/batching", text: "Batching" },
        { link: "/sdk/guides/error-handling", text: "Error Handling" },
        { link: "/sdk/guides/writes", text: "Writes" },
        { link: "/sdk/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    {
      items: [
        { link: "/sdk/api/ensforge", text: "Ensforge" },
        { link: "/sdk/api/create-ensforge", text: "createEnsforge" },
      ],
      text: "Configuration",
    },
    apiGroup("/sdk/api/batch", "Batch Methods", actionGroups.batch),
    apiGroup("/sdk/api/capabilities", "Capabilities Methods", actionGroups.capabilities),
    apiGroup("/sdk/api/dns", "Dns Methods", actionGroups.dns),
    apiGroup("/sdk/api/events", "Events Methods", actionGroups.events),
    apiGroup("/sdk/api/migration", "Migration Methods", actionGroups.migration),
    apiGroup("/sdk/api/name", "Name Methods", actionGroups.name),
    apiGroup("/sdk/api/ownership", "Ownership Methods", actionGroups.ownership),
    apiGroup("/sdk/api/permissions", "Permissions Methods", actionGroups.permissions),
    apiGroup("/sdk/api/records", "Records Methods", actionGroups.records),
    apiGroup("/sdk/api/registration", "Registration Methods", actionGroups.registration),
    apiGroup("/sdk/api/resolution", "Resolution Methods", actionGroups.resolution),
    apiGroup("/sdk/api/reverse", "Reverse Methods", actionGroups.reverse),
    apiGroup("/sdk/api/subnames", "Subnames Methods", actionGroups.subnames),
    apiGroup("/sdk/api/wrapping", "Wrapping Methods", actionGroups.wrapping),
  ],
  "/react/": [
    {
      items: [
        { link: "/react/why", text: "Why ensforge" },
        { link: "/react/installation", text: "Installation" },
        { link: "/react/getting-started", text: "Getting Started" },
        { link: "/react/effect", text: "Effect" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/react/guides/queries", text: "Query Hooks" },
        { link: "/react/guides/mutations", text: "Mutation Hooks" },
        { link: "/react/guides/effect-atom", text: "Effect Atom" },
        { link: "/react/guides/caching", text: "Caching and Invalidation" },
        { link: "/react/guides/suspense", text: "Suspense" },
        { link: "/react/guides/batching", text: "Batching" },
        { link: "/react/guides/error-handling", text: "Error Handling" },
        { link: "/react/guides/ssr", text: "SSR and Frameworks" },
        { link: "/react/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    {
      items: [
        { link: "/react/api/config", text: "Config" },
        { link: "/react/api/ensforge-provider", text: "EnsforgeProvider" },
        { link: "/react/api/atom-options", text: "Atom Options" },
        { link: "/react/api/atom-result", text: "Atom Result" },
        { link: "/react/api/mutation-options", text: "Mutation Options" },
        { link: "/react/api/mutation-result", text: "Mutation Result" },
      ],
      text: "Configuration",
    },
    {
      items: [
        { link: "/react/api/cache/create-registry", text: "createRegistry" },
        { link: "/react/api/cache/prefetch", text: "prefetch" },
        { link: "/react/api/cache/prefetch-effect", text: "prefetchEffect" },
        { link: "/react/api/cache/invalidate", text: "invalidate" },
        {
          link: "/react/api/cache/invalidate-effect",
          text: "invalidateEffect",
        },
        { link: "/react/api/cache/make-invalidation-keys", text: "makeInvalidationKeys" },
      ],
      text: "Cache",
    },
    {
      items: [
        { link: "/react/api/atoms/make-query-atom", text: "makeQueryAtom" },
        { link: "/react/api/atoms/make-mutation-atom", text: "makeMutationAtom" },
        { link: "/react/api/atoms/make-stream-atom", text: "makeStreamAtom" },
        { link: "/react/api/hooks/make-query-hook", text: "makeQueryHook" },
        { link: "/react/api/hooks/make-mutation-hook", text: "makeMutationHook" },
        {
          link: "/react/api/hooks/make-suspense-query-hook",
          text: "makeSuspenseQueryHook",
        },
        { link: "/react/api/hooks/prefetch-atom", text: "prefetchAtom" },
      ],
      text: "Advanced",
    },
    apiGroup("/react/api/hooks/context", "Context Hooks", hookGroups.context),
    apiGroup("/react/api/hooks/cache", "Cache Hooks", hookGroups.cache),
    apiGroup("/react/api/hooks/batch", "Batch Hooks", hookGroups.batch),
    apiGroup("/react/api/hooks/capabilities", "Capabilities Hooks", hookGroups.capabilities),
    apiGroup("/react/api/hooks/dns", "Dns Hooks", hookGroups.dns),
    apiGroup("/react/api/hooks/events", "Events Hooks", hookGroups.events),
    apiGroup("/react/api/hooks/migration", "Migration Hooks", hookGroups.migration),
    apiGroup("/react/api/hooks/name", "Name Hooks", hookGroups.name),
    apiGroup("/react/api/hooks/ownership", "Ownership Hooks", hookGroups.ownership),
    apiGroup("/react/api/hooks/permissions", "Permissions Hooks", hookGroups.permissions),
    apiGroup("/react/api/hooks/records", "Records Hooks", hookGroups.records),
    apiGroup("/react/api/hooks/registration", "Registration Hooks", hookGroups.registration),
    apiGroup("/react/api/hooks/resolution", "Resolution Hooks", hookGroups.resolution),
    apiGroup("/react/api/hooks/reverse", "Reverse Hooks", hookGroups.reverse),
    apiGroup("/react/api/hooks/subnames", "Subnames Hooks", hookGroups.subnames),
    apiGroup("/react/api/hooks/wrapping", "Wrapping Hooks", hookGroups.wrapping),
  ],
  "/contracts/": [
    {
      items: [
        { link: "/contracts/why", text: "Why ensforge" },
        { link: "/contracts/installation", text: "Installation" },
        { link: "/contracts/getting-started", text: "Getting Started" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/contracts/guides/entrypoints", text: "Entrypoints" },
        { link: "/contracts/guides/deployments", text: "Deployments" },
        { link: "/contracts/guides/fragments", text: "ABI Fragments" },
        { link: "/contracts/guides/resolver-profiles", text: "Resolver Profiles" },
        { link: "/contracts/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    contractGroup("Deployments", contractGroups.deployments),
    contractGroup("Shared", contractGroups.shared),
    contractGroup("Resolver Profiles", contractGroups.resolverProfiles),
    contractGroup("V1 ABIs", contractGroups.v1Abis),
    contractGroup("V1 Fragments", contractGroups.v1Fragments),
    contractGroup("V1 Constants", contractGroups.v1Constants),
    contractGroup("V2 ABIs", contractGroups.v2Abis),
    contractGroup("V2 Fragments", contractGroups.v2Fragments),
    contractGroup("V2 Interfaces", contractGroups.v2Interfaces),
    contractGroup("V2 Constants", contractGroups.v2Constants),
    contractGroup("Experimental HCA", contractGroups.experimentalHca),
  ],
};
