import {
  clearAvatar,
  clearRecords,
  getAbi,
  getAddress,
  getAddresses,
  getAvatar,
  getContentHash,
  getData,
  getInterface,
  getName,
  getPubkey,
  getRecords,
  getText,
  getTexts,
  setAbi,
  setAddress,
  setAddresses,
  setAlias,
  setAvatar,
  setContentHash,
  setData,
  setInterface,
  setName,
  setPubkey,
  setRecords,
  setText,
  setTexts,
  type EnsforgeConfig,
} from "@ensforge/core";

import { bindAction } from "../internal/bind-action.js";

export const makeRecordsActions = (config: EnsforgeConfig) =>
  Object.freeze({
    clearAvatar: bindAction(config, clearAvatar),
    clearRecords: bindAction(config, clearRecords),
    getAbi: bindAction(config, getAbi),
    getAddress: bindAction(config, getAddress),
    getAddresses: bindAction(config, getAddresses),
    getAvatar: bindAction(config, getAvatar),
    getContentHash: bindAction(config, getContentHash),
    getData: bindAction(config, getData),
    getInterface: bindAction(config, getInterface),
    getName: bindAction(config, getName),
    getPubkey: bindAction(config, getPubkey),
    getRecords: bindAction(config, getRecords),
    getText: bindAction(config, getText),
    getTexts: bindAction(config, getTexts),
    setAbi: bindAction(config, setAbi),
    setAddress: bindAction(config, setAddress),
    setAddresses: bindAction(config, setAddresses),
    setAlias: bindAction(config, setAlias),
    setAvatar: bindAction(config, setAvatar),
    setContentHash: bindAction(config, setContentHash),
    setData: bindAction(config, setData),
    setInterface: bindAction(config, setInterface),
    setName: bindAction(config, setName),
    setPubkey: bindAction(config, setPubkey),
    setRecords: bindAction(config, setRecords),
    setText: bindAction(config, setText),
    setTexts: bindAction(config, setTexts),
  });

export type RecordsActions = ReturnType<typeof makeRecordsActions>;
